#include "mconf.h"

typedef struct {
    double n;
    double d;
} fract;

extern double MACHEP;
extern double MAXLOG;
extern double MINLOG;
extern double MAXNUM;
extern double PI;
extern double PIO2;
extern double PIO4;
extern double SQRT2;
extern double SQRTH;
extern double LOG2E;
extern double SQ2OPI;
extern double LOGE2; 
extern double LOGSQ2;
extern double THPIO4;
extern double TWOOPI;

extern double md_acosh ( double x );
extern int md_airy ( double x, double *y, double *z, double *u, double *v );
extern double md_asin ( double x );
extern double md_acos ( double x );
extern double md_arcdot ( double *p, double *q );
extern double md_asinh ( double x );
extern double md_atan ( double x );
extern double md_atan2 ( double y, double x );
extern double md_atanh ( double x );
extern double md_bdtrc ( int k, int n, double p );
extern double md_bdtr ( int k, int n, double p );
extern double md_bdtri ( int k, int n, double y );
extern double md_beta ( double a, double b );
extern double md_lbeta ( double a, double b );
extern double md_btdtr ( double a, double b, double x );
extern double md_cbrt ( double x );
extern double md_chbevl ( double x, void *P, int n );
extern double md_chdtrc ( double df, double x );
extern double md_chdtr ( double df, double x );
extern double md_chdtri ( double df, double y );
extern void md_clog ( cmplx *z, cmplx *w );
extern void md_cexp ( cmplx *z, cmplx *w );
extern void md_csin ( cmplx *z, cmplx *w );
extern void md_ccos ( cmplx *z, cmplx *w );
extern void md_ctan ( cmplx *z, cmplx *w );
extern void md_ccot ( cmplx *z, cmplx *w );
extern void md_casin ( cmplx *z, cmplx *w );
extern void md_cacos ( cmplx *z, cmplx *w );
extern void md_catan ( cmplx *z, cmplx *w );
extern void md_csinh ( cmplx *z, cmplx *w );
extern void md_casinh ( cmplx *z, cmplx *w );
extern void md_ccosh ( cmplx *z, cmplx *w );
extern void md_cacosh ( cmplx *z, cmplx *w );
extern void md_ctanh ( cmplx *z, cmplx *w );
extern void md_catanh ( cmplx *z, cmplx *w );
extern void md_cpow ( cmplx *a, cmplx *z, cmplx *w );
extern void md_radd ( fract *a, fract *b, fract *c );
extern void md_rsub ( fract *a, fract *b, fract *c );
extern void md_rmul ( fract *a, fract *b, fract *c );
extern void md_rdiv ( fract *a, fract *b, fract *c );
extern double md_euclid ( double *x, double *y);
extern void md_cadd ( cmplx *a, cmplx *b, cmplx *c );
extern void md_csub ( cmplx *a, cmplx *b, cmplx *c );
extern void md_cmul ( cmplx *a, cmplx *b, cmplx *c );
extern void md_cdiv ( cmplx *a, cmplx *b, cmplx *c );
extern void md_cmov ( void *a, void *b );
extern void md_cneg ( cmplx *a );
extern double md_cabs ( cmplx *z );
extern void md_csqrt ( cmplx *z, cmplx *w );
extern double md_hypot ( double x, double y );
extern double md_cosh ( double x );
extern double md_dawsn ( double xx );
extern double md_ellie ( double phi, double m );
extern double md_ellik ( double phi, double m );
extern double md_ellpe ( double x );
extern int md_ellpj ( double u, double m, double *x, double *y, double *z, double *a );
extern double md_ellpk ( double x );
extern double md_exp ( double x );
extern double md_exp10 ( double x );
/* extern double md_exp1m ( double x ); */
extern double md_exp2 ( double x );
extern double md_expn ( int n, double x );
extern double md_ei ( double x );
extern double md_fabs ( double x );
extern double md_fac ( int i );
extern double md_fdtrc ( int ia, int ib, double x );
extern double md_fdtr ( int ia, int ib, double x );
extern double md_fdtri ( int ia, int ib, double y );
extern double md_ceil ( double x );
extern double md_floor ( double x );
extern double md_frexp ( double x, int *n);
/* extern double md_frexp ( double x, int *pw2 ); */
extern double md_ldexp ( double x, int pw2 );
/* extern int md_signbit ( double x ); */
/* extern int md_isnan ( double x ); */
/* extern int md_isfinite ( double x ); */
extern int md_fresnl ( double xxa, double *x, double *y);
extern double md_gamma ( double x );
extern double md_lgam ( double x );
extern double md_gdtr ( double a, double b, double x );
extern double md_gdtrc ( double a, double b, double x );
extern double md_hyp2f1 ( double a, double b, double c, double x );
extern double md_hyperg ( double a, double b, double x );
extern double md_hyp2f0 ( double a, double b, double x, int type, double *y );
extern double md_i0 ( double x );
extern double md_i0e ( double x );
extern double md_i1 ( double x );
extern double md_i1e ( double x );
extern double md_igamc ( double a, double x );
extern double md_igam ( double a, double x );
extern double md_igami ( double a, double y0 );
extern double md_incbet ( double aa, double bb, double xx );
extern double md_incbi ( double aa, double bb, double yy0 );
extern double md_iv ( double v, double x );
extern double md_j0 ( double x );
extern double md_y0 ( double x );
extern double md_j1 ( double x );
extern double md_y1 ( double x );
extern double md_jn ( int n, double x );
extern double md_jv ( double n, double x );
extern double md_k0 ( double x );
extern double md_k0e ( double x );
extern double md_k1 ( double x );
extern double md_k1e ( double x );
extern double md_kn ( int nn, double x );
extern double md_log ( double x );
extern double md_log10 ( double x );
extern double md_log2 ( double x );
extern long md_lrand ( void );
extern long md_lsqrt ( long x );
extern int md_mtherr ( char *name, int code );
extern double md_polevl ( double x, void *P, int N );
extern double md_p1evl ( double x, void *P, int N );
extern double md_nbdtrc ( int k, int n, double p );
extern double md_nbdtr ( int k, int n, double p );
extern double md_nbdtri ( int k, int n, double p );
extern double md_ndtr ( double a );
extern double md_erfc ( double a );
extern double md_erf ( double x );
extern double md_ndtri ( double y0 );
extern double md_pdtrc ( int k, double m );
extern double md_pdtr ( int k, double m );
extern double md_pdtri ( int k, double y );
extern double md_pow ( double x, double y );
extern double md_powi ( double x, int nn );
extern double md_psi ( double x );
extern double md_rgamma ( double x );
extern double md_round ( double x );
extern int md_shichi ( double x, double *y, double *z );
extern int md_sici ( double x, double *y, double *z );
extern double md_sin ( double x );
extern double md_cos ( double x );
extern double md_radian ( double d, double m, double s );
/*
extern int md_sincos ( double x, double *y, double *z, int flg );
*/
extern double md_sindg ( double x );
extern double md_cosdg ( double x );
extern double md_sinh ( double x );
extern double md_spence ( double x );
extern double md_sqrt ( double x );
extern double md_stdtr ( int k, double t );
extern double md_stdtri ( int k, double p );
extern double md_onef2 ( double a, double b, double c, double x, double *y );
extern double md_threef0 ( double a, double b, double c, double x, double *y );
extern double md_struve ( double v, double x );
extern double md_tan ( double x );
extern double md_cot ( double x );
extern double md_tandg ( double x );
extern double md_cotdg ( double x );
extern double md_tanh ( double x );
extern double md_log1p ( double x );
extern double md_expm1 ( double x );
extern double md_cosm1 ( double x );
extern double md_yn ( int n, double x );
extern double md_yv ( double n, double x );
extern double md_zeta ( double x, double q );
extern double md_zetac ( double x );
extern int md_drand ( double *x );

extern double md_plancki(double w, double T);

extern void md_polini( int maxdeg );
extern void md_polclr ( double * A, int n);
extern void md_polmov ( double * A, int na, double * B );
extern void md_polmul ( double * A, int na, double * B, int nb, double * C );
extern int md_poldiv ( double * A, int na, double * B, int nb, double * C);
extern void md_poladd ( double * A, int na, double * B, int nb, double * C );
extern void md_polsub ( double * A, int na, double * B, int nb, double * C );
extern void md_polsbt ( double * A, int na, double * B, int nb, double * C );
extern void md_polprt ( double * A, int na, int d );
extern double md_poleva (double * A, int na, double x);
extern void md_polatn(double * A, double * B, double * C, int n);
extern void md_polsqt(double * A, double * B, int n);
extern void md_polsin(double * A, double * B, int n);
extern void md_polcos(double * A, double * B, int n);
extern int md_polrt_wrap(double * xcof, double * cof, int m, double * r, double * i);

extern void md_bernum_wrap(double * num, double * den);
extern double md_simpsn_wrap(double * f, int n, double h);
extern int md_minv(double * A, double * X, int n, double * B, int * IPS);
extern void md_mtransp(int n, double * A, double * X);
extern void md_eigens(double * A, double * EV, double * E, int n);
extern int md_simq(double * A, double * B, double * X, int n, int flag, int * IPS);
extern double md_polylog(int n, double x);
extern double md_arcdot(double * p, double * q);
extern double md_expx2(double x, int sign);
